In [30]:
import numpy as np

In [50]:
l = []

In [51]:
a = np.random.randint(3, 45, 10)

In [52]:
a

array([12, 34, 17, 16, 16, 35, 19, 32, 31, 30])

In [53]:
a[0]

12

In [54]:
len(a)

10

In [56]:
for i in a:
    print(i)

12
34
17
16
16
35
19
32
31
30


## Converitng array using indexing in For Loop

In [57]:
# puting array eliment into list
for i in a:
    l.append(i)

In [58]:
l

[12, 34, 17, 16, 16, 35, 19, 32, 31, 30]

In [59]:
type(a)

numpy.ndarray

In [60]:
type(l)

list

## Converting Array using tolist() function

In [61]:
b = a.copy()

In [62]:
b

array([12, 34, 17, 16, 16, 35, 19, 32, 31, 30])

In [63]:
#converting b array to list
b = b.tolist()

In [64]:
b

[12, 34, 17, 16, 16, 35, 19, 32, 31, 30]

## Python Memoization

In [23]:
# Fibonacci Number
# 3! = 3*2*1
# Using Memoization 
from functools import lru_cache
@lru_cache(maxsize = 500)

# fibo_cache = {}

# def fibo(n):
#     if n in fibo_cache:
#         return fibo_cache[n]
#     if n==1:
#         val = 1
#     elif n==2:
#         val = 2
#     elif n>2:
#         val = fibo(n-1)+fibo(n-2)
        
#     fibo_cache[n] = val
#     return val
        
def fibo(n):
    if n == 1:
        return 1
    elif n == 2:
        return 2
    elif n>2:
        return fibo(n-1) + fibo(n-2)

In [28]:
for n in range (10):
    print(n, ":", fibo(n))

0 : None
1 : 1
2 : 2
3 : 3
4 : 5
5 : 8
6 : 13
7 : 21
8 : 34
9 : 55


## Linear Search

In [31]:
a = np.random.randint(5, 55, 10)

In [32]:
a

array([46,  5, 17, 23, 46, 52, 19, 27, 15, 25])

In [33]:
b = a.copy()

In [35]:
b = b.tolist()

In [36]:
b

[46, 5, 17, 23, 46, 52, 19, 27, 15, 25]

In [52]:
def linear_search(l, t):
    for i in l:
        if i==t:
            found = t
            return f"{t} found in the lit at inde {i}"
    return f"{t} is not found in {l}"

In [53]:
linear_search(b, 19)

'19 found in the lit at inde 19'

In [55]:
# Or Using Index
def linear_search1(l, t):
    for i in range(0, len(l)-1):
        if l[i] == t:
            found = t
            return f"{found} is found at index {i}"
    return f"{t} is not found in the list {l}"

In [56]:
linear_search(b, 10)

'10 is not found in [46, 5, 17, 23, 46, 52, 19, 27, 15, 25]'

In [58]:
linear_search1(b, 10)

'10 is not found in the list [46, 5, 17, 23, 46, 52, 19, 27, 15, 25]'

In [60]:
linear_search1(b, 19)

'19 is found at index 6'