In [30]:
import numpy as np

In [50]:
l = []

In [51]:
a = np.random.randint(3, 45, 10)

In [52]:
a

array([12, 34, 17, 16, 16, 35, 19, 32, 31, 30])

In [53]:
a[0]

12

In [54]:
len(a)

10

In [56]:
for i in a:
    print(i)

12
34
17
16
16
35
19
32
31
30


## Converitng array using indexing in For Loop

In [57]:
# puting array eliment into list
for i in a:
    l.append(i)

In [58]:
l

[12, 34, 17, 16, 16, 35, 19, 32, 31, 30]

In [59]:
type(a)

numpy.ndarray

In [60]:
type(l)

list

## Converting Array using tolist() function

In [61]:
b = a.copy()

In [62]:
b

array([12, 34, 17, 16, 16, 35, 19, 32, 31, 30])

In [63]:
#converting b array to list
b = b.tolist()

In [64]:
b

[12, 34, 17, 16, 16, 35, 19, 32, 31, 30]

## Explicit Implementation of Python Chache

In [10]:
fibo_cache = {}

def fibo_cv(n):
    # if have cached value then directly return the value
    if n in fibo_cache:
        return fibo_cache[n]
    
    # otherwise compute fibonacci
    if n==1:
        val = 1
    elif n==2:
        val = 2
    elif n>2:
        val = fibo_cv(n-1) + fibo_cv(n-2)

    # cache the value and return
    fibo_cache[n] = val
    return val

In [11]:
for n in range (1, 100):
    print(n, ":", fibo_cv(n))

1 : 1
2 : 2
3 : 3
4 : 5
5 : 8
6 : 13
7 : 21
8 : 34
9 : 55
10 : 89
11 : 144
12 : 233
13 : 377
14 : 610
15 : 987
16 : 1597
17 : 2584
18 : 4181
19 : 6765
20 : 10946
21 : 17711
22 : 28657
23 : 46368
24 : 75025
25 : 121393
26 : 196418
27 : 317811
28 : 514229
29 : 832040
30 : 1346269
31 : 2178309
32 : 3524578
33 : 5702887
34 : 9227465
35 : 14930352
36 : 24157817
37 : 39088169
38 : 63245986
39 : 102334155
40 : 165580141
41 : 267914296
42 : 433494437
43 : 701408733
44 : 1134903170
45 : 1836311903
46 : 2971215073
47 : 4807526976
48 : 7778742049
49 : 12586269025
50 : 20365011074
51 : 32951280099
52 : 53316291173
53 : 86267571272
54 : 139583862445
55 : 225851433717
56 : 365435296162
57 : 591286729879
58 : 956722026041
59 : 1548008755920
60 : 2504730781961
61 : 4052739537881
62 : 6557470319842
63 : 10610209857723
64 : 17167680177565
65 : 27777890035288
66 : 44945570212853
67 : 72723460248141
68 : 117669030460994
69 : 190392490709135
70 : 308061521170129
71 : 498454011879264
72 : 806515533049393
73

## Python Memoization - using lru_cache 
### lru -> Least Recently Used Cache

In [14]:
# Fibonacci Number
# 3! = 3*2*1
# Using Memoization 
from functools import lru_cache

@lru_cache(maxsize = 500) #500 values of this function it'will cache      
def fibo(n):
    if n == 1:
        return 1
    elif n == 2:
        return 2
    elif n>2:
        return fibo(n-1) + fibo(n-2)

In [13]:
for n in range (1, 100):
    print(n, ":", fibo(n))

1 : 1
2 : 2
3 : 3
4 : 5
5 : 8
6 : 13
7 : 21
8 : 34
9 : 55
10 : 89
11 : 144
12 : 233
13 : 377
14 : 610
15 : 987
16 : 1597
17 : 2584
18 : 4181
19 : 6765
20 : 10946
21 : 17711
22 : 28657
23 : 46368
24 : 75025
25 : 121393
26 : 196418
27 : 317811
28 : 514229
29 : 832040
30 : 1346269
31 : 2178309
32 : 3524578
33 : 5702887
34 : 9227465
35 : 14930352
36 : 24157817
37 : 39088169
38 : 63245986
39 : 102334155
40 : 165580141
41 : 267914296
42 : 433494437
43 : 701408733
44 : 1134903170
45 : 1836311903
46 : 2971215073
47 : 4807526976
48 : 7778742049
49 : 12586269025
50 : 20365011074
51 : 32951280099
52 : 53316291173
53 : 86267571272
54 : 139583862445
55 : 225851433717
56 : 365435296162
57 : 591286729879
58 : 956722026041
59 : 1548008755920
60 : 2504730781961
61 : 4052739537881
62 : 6557470319842
63 : 10610209857723
64 : 17167680177565
65 : 27777890035288
66 : 44945570212853
67 : 72723460248141
68 : 117669030460994
69 : 190392490709135
70 : 308061521170129
71 : 498454011879264
72 : 806515533049393
73

## Linear Search

In [31]:
a = np.random.randint(5, 55, 10)

In [32]:
a

array([46,  5, 17, 23, 46, 52, 19, 27, 15, 25])

In [33]:
b = a.copy()

In [35]:
b = b.tolist()

In [36]:
b

[46, 5, 17, 23, 46, 52, 19, 27, 15, 25]

In [63]:
def linear_search(l, t):
    for i in l:
        if i==t:
            found = t
            return f"{t} found in the lit"
    return f"{t} is not found in {l}"

In [64]:
linear_search(b, 19)

'19 found in the lit'

In [65]:
# Or Using Index position
def linear_search1(l, t):
    for i in range(0, len(l)-1):
        if l[i] == t:
            found = t
            return f"{found} is found at index {i}"
    return f"{t} is not found in the list {l}"

In [66]:
linear_search(b, 10)

'10 is not found in [46, 5, 17, 23, 46, 52, 19, 27, 15, 25]'

In [67]:
linear_search1(b, 10)

'10 is not found in the list [46, 5, 17, 23, 46, 52, 19, 27, 15, 25]'

In [68]:
linear_search1(b, 19)

'19 is found at index 6'

## Binary Search

In [71]:
def binary_search(l, t):
    first = 0
    last = len(l)-1
    
    while first <= last:
        mid = (len(l)-1)//2 # floor div
        
        if l[mid] == t:
            return f"{t} found at index {mid}"
        elif l[mid] < t:
            first = mid + 1
        else:
            last = mid -1
    return f"{t} found in the {l}"
        
        